### ISSUE TITLE
want to add code for 0-1 Knapsack

### ISSUE THREAD

**Issue by Navidulhaque** [SarthakKeshari/CPP-Questions-and-Solutions#506]
### A brief about your proposal - 
hi their ,
I want to add the Tabulation method code for 0-1 knapsack problem in
 CPP-Questions-and-Solutions/Dynamic Programming/
Please allow me to do this

**Comment by SarthakKeshari** [comment]
@Navidulhaque,
Kindly check the repo. I guess think issue has been addressed.

**Comment by Navidulhaque** [comment]
@SarthakKeshari  knapsack solution present at CPP-Questions-and-Solutions/Dynamic Programming/ is not solved using dynamic programming it is solved using recursion. So, kindly allow me to add a dynamic programming solution their.

**Comment by SarthakKeshari** [comment]
@Navidulhaque,
Ok, I wish to see your approach, go ahead. I will review it.
Kindly add your solution to "Dynamic Programming" folder.
Deadline - 20/10/2021
